---
AWSTemplateFormatVersion: "2010-09-09"
Description: "A Simple Example"
Resources:
  myec2:
    Type: "AWS::EC2::Instance"
    Properties:
      ImageId: "ami-08df646e18b182346"
      InstanceType: "t2.micro"
      KeyName: "mykey"
